Tool Group Names:
  - PickAxe
  - Axe
  - Shovel
  - Hoe
  - Weapons
Tool Groups:
  PickAxe:
    Delete Untracked Stats: true
    Tools:
       - WOODEN_PICKAXE
       - STONE_PICKAXE
       - IRON_PICKAXE
       - GOLDEN_PICKAXE
       - DIAMOND_PICKAXE
       - NETHERITE_PICKAXE
    Blocks Destroyed:
      Color: '&7'
      Count Color: '&f'
      Track Stats: true
      Update Preexisting Tools: true
      Header: 'Blocks Mined'
      Materials:
        - STONE
        - COAL_ORE
        - IRON_ORE
        - GOLD_ORE
        - DIAMOND_ORE
        - EMERALD_ORE
        - ANCIENT_DEBRIS
        - REDSTONE_ORE
        - LAPIS_ORE
        - Total
  Axe:
    Delete Untracked Stats: true
    Tools:
      - WOODEN_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLDEN_AXE
      - DIAMOND_AXE
      - NETHERITE_AXE
    Blocks Destroyed:
      Color: '&7'
      Count Color: '&f'
      Track Stats: true
      Update Preexisting Tools: true
      Header: 'Blocks Chopped'
      Materials:
        - OAK_LOG
        - BIRCH_LOG
        - ACACIA_LOG
        - JUNGLE_LOG
        - SPRUCE_LOG
        - DARK_OAK_LOG
        - Total
  Shovel:
    Delete Untracked Stats: true
    Tools:
      - WOODEN_SHOVEL
      - STONE_SHOVEL
      - IRON_SHOVEL
      - GOLDEN_SHOVEL
      - DIAMOND_SHOVEL
      - NETHERITE_SHOVEL
    Blocks Destroyed:
      Color: '&7'
      Count Color: '&f'
      Track Stats: true
      Update Preexisting Tools: true
      Header: 'Blocks Dug'
      Materials:
        - DIRT
        - CLAY
        - SAND
        - SNOW
        - PODZOL
        - GRAVEL
        - MYCELIUM
        - SOUL_SAND
        - GRASS_BLOCK
        - Total
  Hoe:
    Delete Untracked Stats: true
    Tools:
      - WOODEN_HOE
      - STONE_HOE
      - IRON_HOE
      - GOLDEN_HOE
      - DIAMOND_HOE
      - NETHERITE_HOE
    Blocks Tilled:
      Color: '&7'
      Count Color: '&f'
      Track Stats: true
      Update Preexisting Tools: true
      Header: 'Blocks Tilled'
      Materials:
        - DIRT
        - COARSE_DIRT
        - GRASS_PATH
        - GRASS_BLOCK
        - Total
  Weapons:
    Delete Untracked Stats: true
    Tools:
      - WOODEN_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLDEN_AXE
      - DIAMOND_AXE
      - WOODEN_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLDEN_SWORD
      - DIAMOND_SWORD
      - NETHERITE_AXE
      - NETHERITE_SWORD
      - BOW
      - CROSSBOW
      - TRIDENT
    Mobs Killed:
      Color: '&7'
      Count Color: '&f'
      Track Stats: true
      Update Preexisting Tools: true
      Header: 'Mobs Killed'
      Entity Types:
        - SPIDER
        - ZOMBIE
        - CREEPER
        - SKELETON
        - ENDERMAN
        - Player
        - Total
    