main: plugins.smokyminer.toolstats.ToolStats
name: ToolStats
version: 1.0
author: SmokyMiner
description: Keeps Track Of Tool Statistics
api-version: 1.13
commands:
  ts:
    description: Tool Stats command prefix
    usage: /ts [command]