main: plugins.smokyminer.toolstats.ToolStats
name: ToolStats
version: 3.0
author: SmokyMiner
description: Records statistics for tools
api-version: 1.13
commands:
  ts:
    description: Tool Stats command prefix
    usage: /<command> [command]
permissions:
  toolstats.track.*:
    description: Gives access to tool tracking by all Tool Groups
    default: true
  toolstats.reload:
    description: Gives access to "reload" command
    default: op
  toolstats.toggle:
    description: Gives access to "hide" and "show" commands
    default: true
    children:
      toolstats.hide: true
      toolstats.show: true
  toolstats.hide:
    description: Gives access to "hide" command
  toolstats.show:
    description: Gives access to "show" command